...

diff --git a/src/bin/mcsrv b/src/bin/mcsrv
--- a/src/bin/mcsrv
+++ b/src/bin/mcsrv
@@ -78,7 +78,7 @@ _mcsrv_set_defaults() {
 ###############
 
 # Source main library
-source /usr/local/bin/minectl 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
+source /usr/local/etc/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
 
 if [ $# -ne 1 ]; then
 	print --fail "Usage: `basename $0` <server_name>" 
diff --git a/src/bin/minectl b/src/bin/minectl
--- a/src/bin/minectl
+++ b/src/bin/minectl
@@ -250,7 +250,7 @@ require() {
 #####################
 # Load main library #
 #####################
-require minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
+source /usr/local/etc/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
 
 # Read plugin list
 if [ -f "$PLUGINS_LIST" ]; then
