,,,

diff --git a/src/bin/mcsrv b/src/bin/mcsrv
--- a/src/bin/mcsrv
+++ b/src/bin/mcsrv
@@ -21,6 +21,9 @@
 # Global variables #
 ####################
 
+# Source main library
+source /usr/local/etc/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
+
 # First parameter is the server's name
 SERVER_NAME="$1"
 
@@ -76,9 +79,6 @@ _mcsrv_set_defaults() {
 ###############
 # Main script #
 ###############
-
-# Source main library
-source /usr/local/etc/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
 
 if [ $# -ne 1 ]; then
 	print --fail "Usage: `basename $0` <server_name>" 
