Relocated functions to minelib, renamed functions with unit prefixes, altered source file system structure, added event handling

diff --git a/src/bin/mcsrv b/src/bin/mcsrv
--- a/src/bin/mcsrv
+++ b/src/bin/mcsrv
@@ -21,35 +21,24 @@
 # Global variables #
 ####################
 
-# Minectl's home directory
-MC_HOME="/home/minectl"
-
-# The directory containing the servers
-SERVERS_DIR="$MC_HOME/servers"
+# First parameter is the server's name
+SERVER_NAME="$1"
 
 # The directory containing the libraries
 LIB_DIR="/usr/local/libexec/minectl"
 
-# The shared library's path
-MC_LIB="$LIB_DIR/minelib"
-
-# The meta-config file's name
-CFG_FILE=./.mcsrv.cfg
-
-# The name of the server
-SERVER_NAME=$1
+# Indicate failure when loading of shared library fails
+lib_fail() {
+	echo "Could not load main library" 1>&2
+	exit 1
+}
 
 ###############
 # Main script #
 ###############
 
-# Check for shared library
-if [ -f $MC_LIB ]; then
-	. $MC_LIB
-else
-	echo -e "Shared library could not be found" 1>&2
-	exit 1
-fi
+# Source main library
+source /usr/local/libexec/minectl/minelib 2> /dev/null || lib_fail
 
 if [ $# -ne 1 ]; then
 	fail "Usage: `basename $0` <server_name>" 
@@ -59,7 +48,7 @@ fi
 access_server "$SERVER_NAME" || fail
 
 # Source configuration file
-. $CFG_FILE 2> /dev/null || fail "Configuration file is missing"
+source $SERVER_CONFIG 2> /dev/null || fail "Configuration file is missing"
 
 # Set default values for required 
 # configuration parameters
@@ -85,4 +74,4 @@ if [ -n "$NICENESS" ]; then
 fi
 
 # Start the server and connect it to the named pipes
-exec $EXEC 0<> stdin 1<> stdout 2<> stderr
+exec $EXEC 0<> stdin 1> stdout 2| tee -a "$LOGFILE" | tee events > stderr
diff --git a/src/libexec/minelib b/src/libexec/minelib
--- a/src/libexec/minelib
+++ b/src/libexec/minelib
@@ -2,7 +2,7 @@
 #
 #	minelib - Library for functions frequently used by minectl's scripts
 #
-#	Version 1.0
+#	Version 2.0
 #
 #	Copyright (C) 2012 Richard Neumann <mail@richard-neumann.de>
 #
@@ -19,12 +19,77 @@
 #	You should have received a copy of the GNU General Public License
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-###########################
-# Miscellaneous functions #
-###########################
+####################
+# Global variables #
+####################
+
+# Define default minectl user
+export MC_USER=minectl
+
+### Absolute paths ###
+
+# Define home directory
+export MC_HOME="/home/$MC_USER"
+
+# The directory containing the servers
+export SERVERS_DIR="$MC_HOME/servers"
+
+# Name of the event scripts
+export EVENT_HANDLERS_DIR="$MC_HOME/event-handlers"
+
+# The shared library's path
+export MC_LIB="$LIB_DIR/minelib"
+
+# Binaries' directory
+export BIN_DIR="/usr/local/bin"
+
+# Library directory
+export LIB_DIR="/usr/local/libexec/$MC_USER"
+
+# JARs' directory
+export JAR_DIR="$LIB_DIR/jar"
+
+# JARs' repository
+export JAR_REPO="$LIB_DIR/jar-repo"
+
+### Paths relative to server ###
+
+# The server's log file
+export SERVER_LOG_FILE="./srv.log"
+
+# Define our configuration file name
+export SERVER_CONFIG="./.mcsrv.cfg"
+
+# The server's properties file
+export SERVER_PROPERTIES="./server.properties"
+
+# The server's white-list
+export SERVER_WHITE_LIST="./white-list.txt"
+
+# The server's ops-list
+export SERVER_OP_LIST="./ops.txt"
+
+# Name of the event queue FIFO pipe
+export SERVER_EVENT_QUEUE="./events"
+
+# Name of the event scripts
+export SERVER_EVENT_HANDLERS_DIR="./eh.d"
+
+# The server's stdin pipe
+export SERVER_STDIN="./stdin"
+
+# The server's stdout pipe
+export SERVER_STDOUT="./stdout"
+
+# The server's stderr pipe
+export SERVER_STDERR="./stderr"
+
+####################
+# Global functions #
+####################
 
 # Inform user about operations being executed
-prompt() {
+minelib_prompt() {
         local -u MSG_TYPE="$1"
 	local MSG_VAR="ASK_$MSG_TYPE"
 	local MSG=${!MSG_VAR}
@@ -37,8 +102,8 @@ prompt() {
 	fi
 }
 
-# New function for displaying errors
-notify() {
+# New function for displaying minelib_err ors
+minelib_notify() {
 	local -u MSG_TYPE="$1"
 	local MSG_VAR="NOTIFY_$MSG_TYPE"
 	local MSG=${!MSG_VAR}
@@ -51,11 +116,11 @@ notify() {
 	fi
 }
 
-# New function for displaying errors
-err() {
+# New function for displaying minelib_err ors
+minelib_err () {
 	if [ -n "$1" ]; then
 		local -u MSG_TYPE="$1"
-		local MSG_VAR="ERR_$MSG_TYPE"
+		local MSG_VAR="minelib_err _$MSG_TYPE"
 		local CODE_VAR="CODE_$MSG_TYPE"
 		local MSG=${!MSG_VAR}
 		local CODE=${!CODE_VAR}
@@ -77,15 +142,15 @@ err() {
 			fi
 		fi
 	else
-		echo -e "[   error   ]" 1>&2
+		echo -e "[   minelib_err or   ]" 1>&2
 		return 1
 	fi
 }
 
 # New function for displaying fails
-fail() {
+minelib_fail() {
 	if [ -n "$1" ]; then
-		err "$@"
+		minelib_err  "$@"
 		exit $?
 	else
 		echo -e "[  failed   ]" 1>&2
@@ -95,7 +160,7 @@ fail() {
 		
 
 # List (just) directories in the current folder (without sub directories)
-ls_dir() {
+minelib_ls_dir() {
 	local DIR="$1"
 
 	if [ -z "$DIR" ]; then
@@ -106,7 +171,7 @@ ls_dir() {
 }
 
 # Operate on files
-fileop() {
+minelib_fileop() {
 	local GREP="grep"
 	local IGNORE_CASE=false
 	local BEGINS_WITH=false
@@ -114,13 +179,13 @@ fileop() {
 	local CMD=
 
 	# Add a string to a file
-	fileop_add() {
+	minelib_fileop_add() {
 		echo "$PATTERN" >> "$FILE"
 		return $?
 	}
 
 	# Check if a certain string is contained in a file
-	fileop_contains() {
+	minelib_fileop_contains() {
 		if ( $BEGINS_WITH && $ENDS_WITH ); then
 			$GREP -E "^$PATTERN[[:blank:]]*$" "$FILE" 2> /dev/null
 		elif ( $BEGINS_WITH ); then
@@ -135,7 +200,7 @@ fileop() {
 	}
 
 	# Remove a string that is in the beginning of a file from this file
-	fileop_remove() {
+	minelib_fileop_remove() {
 		while read MATCH; do
 			local TMP="`mktemp`"		
 			grep -v "$MATCH" "$FILE" > "$TMP" 2> /dev/null
@@ -170,26 +235,26 @@ fileop() {
 	local FILE="$3"
 
 	case $CMD in
-		contains)	fileop_contains
+		contains)	minelib_fileop_contains
 		;;
 		remove)		local TMP_FILE="`mktemp`"
-				fileop_contains > "$TMP_FILE"
-				fileop_remove "$TMP_FILE"
+				minelib_fileop_contains > "$TMP_FILE"
+				minelib_fileop_remove "$TMP_FILE"
 				rm -f "$TMP_FILE" 2> /dev/null
 		;;
-		add)		fileop_add
+		add)		minelib_fileop_add
 		;;
-		*)		error "Unknown file operation \"CMD\""
+		*)		minelib_err or "Unknown file operation \"CMD\""
 	esac
 }
 
 # Extract data from a file removing comments and empty lines
-extract_data() {
+minelib_extract_data() {
 	grep -vE "^[[:blank:]]*$|^[[:blank:]]*#" $1 2> /dev/null
 }
 
 # Ask a question and return 0 on 'yes' or 1 otherwise
-ask() {
+minelib_ask() {
 	local USAGE="\
 	Usage: ask [The question]\nReturns 0 on \"y\" or 1 else."
 
@@ -226,7 +291,7 @@ ask() {
 }
 
 # Change the value of a variable inside a file
-set_var() {
+minelib_set_var() {
 	# Arguments for variable name declaration
 	local DECLARE_ARGS=
 
@@ -253,23 +318,23 @@ set_var() {
 		# we want the variable to be removed from the file
 		if [ -n "`echo "$VARIABLE_PURE" | grep ^"-" 2> /dev/null`" ]; then
 			VARIABLE_PURE="`echo "$VARIABLE_PURE" | cut -d "-" -f 2`"
-			fileop -b remove "$VARIABLE_PURE" "$FILE" 2> /dev/null
+			minelib_fileop -b remove "$VARIABLE_PURE" "$FILE" 2> /dev/null
 		else
 			# Search for variable inside the file	
 			local VAR_LINE="`grep ^"$VARIABLE=" "$FILE" 2> /dev/null`"
 
 			# If the variable is in the file, replace it with its new value
-			if ( fileop -b contains "$VARIABLE=" "$FILE" > /dev/null 2> /dev/null ); then #/dev/null 2> /dev/null ); then
+			if ( minelib_fileop -b contains "$VARIABLE=" "$FILE" > /dev/null 2> /dev/null ); then
 				sed -i "s|$VAR_LINE|$VARIABLE=$VALUE|" "$FILE" 2> /dev/null
 			else
-				fileop add "$VARIABLE=$VALUE" "$FILE"
+				minelib_fileop add "$VARIABLE=$VALUE" "$FILE"
 			fi
 
 			# Print out the new variable assignment
 			echo "$VARIABLE=$VALUE"
 		fi
 	else
-		error "No variable specified"
+		minelib_err or "No variable specified"
 		return 2
 	fi
 	
@@ -278,7 +343,7 @@ set_var() {
 
 # Print out a file and highlight changes. Usage:
 # print_file [--offset, -o <offset>] <file_name> [change_log]
-print_file() {
+minelib_print_file() {
 	local OFFSET=""
 
 	# Check if we specified an offset
@@ -316,30 +381,43 @@ print_file() {
 # if a user does not specify a server name by mistake, we will change to $MC_HOME/servers 
 # and, if clean is called "clean()", may remove all servers by mistake. That won't be good!
 # 'access_server' also makes sure that a certain server (directory) exists
-access_server() {
+minelib_access_server() {
 	# First parameter is the server name
 	# XXX: This variable needs to be global!
 	SERVER_NAME="$1"
 	
 	# Check is server name is not empty
-	test -n "$SERVER_NAME" 2> /dev/null || fail no_srv_name
+	test -n "$SERVER_NAME" 2> /dev/null || minelib_fail no_srv_name
 
 	# Check whether server's directory exists
-	test -d "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || fail srv_not_existant
+	test -d "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || minelib_fail srv_not_existant
 
 	# Check whether server's directory is accessible
-	cd "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || fail access_srv_dir_failed
+	cd "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || minelib_fail access_srv_dir_failed
 
 	# Check if we did really change to a subfolder of $MC_HOME/servers
-	test "`dirname $PWD`" == "$SERVERS_DIR" 2> /dev/null || fail inside_srv_dir
+	test "`dirname $PWD`" == "$SERVERS_DIR" 2> /dev/null || minelib_fail inside_srv_dir
+}
+
+# Clean up the server directory
+minelib_clean() {
+	# First parameter is the server name
+	SERVER_NAME=$1
+	shift
+
+	# Change to server's directory
+	access_server "$SERVER_NAME"
+
+	# Remove server directory's content
+	rm -R * > /dev/null 2> /dev/null || minelib_fail srv_clean_failed
 }
 
 # Create named pipes
-mk_fifos() {
-        for FIFO in stdin stdout stderr; do
+minelib_mk_fifos() {
+        for FIFO in $SERVER_STDIN $SERVER_STDOUT $SERVER_STDERR $SERVER_EVENT_QUEUE; do
                 if [ -e $FIFO ]; then
                         if [ ! -p $FIFO ]; then
-                                fail file_blocking_pipe
+                                minelib_fail file_blocking_pipe
                         fi
                 else
                         mkfifo $FIFO
