Fixed events and mcsrv

diff --git a/src/bin/mcsrv b/src/bin/mcsrv
--- a/src/bin/mcsrv
+++ b/src/bin/mcsrv
@@ -24,9 +24,6 @@
 # First parameter is the server's name
 SERVER_NAME="$1"
 
-# The directory containing the libraries
-LIB_DIR="/usr/local/libexec/minectl"
-
 # Handle events
 mcsrv_handle_events() {
 	# Read the server's stderr fifo
@@ -81,7 +78,7 @@ mcsrv_set_defaults() {
 ###############
 
 # Source main library
-source /usr/local/libexec/minectl/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
+source /usr/local/libexec/minecraft/minelib 2> /dev/null || { echo "Could not load main library" 1>&2; exit 1; }
 
 if [ $# -ne 1 ]; then
 	minelib_fail "Usage: `basename $0` <server_name>" 
