Made minectl modular. Highly experimental

diff --git a/src/libexec/minelib b/src/libexec/minelib
--- a/src/libexec/minelib
+++ b/src/libexec/minelib
@@ -1,8 +1,8 @@
 #! /bin/bash
 #
-#	minelib - Library for functions frequently used by minectl's scripts
+#	minelib - Library for functions frequently used by minectl's plugins
 #
-#	Version 2.0
+#	Version 3.0
 #
 #	Copyright (C) 2012 Richard Neumann <mail@richard-neumann.de>
 #
@@ -19,152 +19,87 @@
 #	You should have received a copy of the GNU General Public License
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-####################
-# Global variables #
-####################
 
-# Define default minectl user
-export MC_USER=minecraft
+#####################
+# Private functions #
+#####################
 
-### Absolute paths ###
+# Test if input is an integer
+_minelib_is_int() {
+	local INT=$1
 
-# Define home directory
-export MC_HOME="/srv/$MC_USER"
-
-# Define backup directory
-export MC_BACKUP="$MC_HOME/backup"
-
-# The directory containing the servers
-export SERVERS_DIR="$MC_HOME/servers"
-
-# JARs' directory
-export JAR_DIR="$MC_HOME/jar"
-
-# Define repository list
-export REPO_LIST="$JAR_DIR/.repolist"
-
-# Name of the event scripts
-export EVENT_HANDLERS_DIR="$MC_HOME/event-handlers"
-
-# Binaries' directory
-export BIN_DIR="/usr/local/bin"
-
-# Library directory
-export LIB_DIR="/usr/local/libexec/$MC_USER"
-
-### Paths relative to server ###
-
-# The server's log file
-export SERVER_LOG_FILE="./mcsrv.log"
-
-# Define our configuration file name
-export SERVER_CONFIG="./.mcsrv.cfg"
-
-# The server's properties file
-export SERVER_PROPERTIES="./server.properties"
-
-# The server's white-list
-export SERVER_WHITE_LIST="./white-list.txt"
-
-# The server's ops-list
-export SERVER_OP_LIST="./ops.txt"
-
-# Name of the event scripts
-export SERVER_EVENT_HANDLERS_DIR="./eh.d"
-
-### Pipes ###
-
-# The server's stdin pipe
-export SERVER_STDIN="./.stdin"
-
-# The server's stdout pipe
-export SERVER_STDOUT="./.stdout"
-
-# The server's stderr pipe
-export SERVER_STDERR="./.stderr"
-
-####################
-# Global functions #
-####################
-
-# Display prompt before reading stuff from CMD line
-minelib_prompt() {
-        local -u MSG_TYPE="$1"
-	local MSG_VAR="ASK_$MSG_TYPE"
-	local MSG=${!MSG_VAR}
-
-	if [ -n "$MSG" ]; then
-		shift
-		echo -en "$MSG $@"
-	else
-		echo -en "$@ "
-	fi
+	test $INT -eq $INT 2> /dev/null
 }
 
 # Display stuff
-minelib_print() {
-	echo -e "$@"
-}
+_minelib_print() {
+	local STDERR=false
 
-# Display notifications
-minelib_notify() {
-	local -u MSG_TYPE="$1"
-	local MSG_VAR="NOTIFY_$MSG_TYPE"
-	local MSG=${!MSG_VAR}
+	local FAIL=false
+	local RETVAL=0
 
-	if [ -n "$MSG" ]; then
+	local ON_DEBUG_LEVEL=0
+	local ECHO_ARGS=""
+	local MESSAGE=""
+
+	while (( $# )); do
+		case $1 in
+			--stdout|-1)	STDERR=false
+			;;
+			--stderr|-2)	STDERR=true
+			;;
+			--level|-l)	ON_DEBUG_LEVEL=$2
+					shift
+			;;
+			--error)	STDERR=true
+					if ( _minelib_is_int $2 ); then
+						RETVAL=$2
+						shift
+					else
+						RETVAL=1
+					fi
+			;;
+			--fail)		STDERR=true
+					FAIL=true
+					if ( _minelib_is_int $2 ); then
+						RETVAL=$2
+						shift
+					else
+						RETVAL=2
+					fi
+			;;
+			-n)		ECHO_ARGS="$ECHO_ARGS -n"
+			;;
+			*)		MESSAGE="$*"
+					break
+		esac
 		shift
-		echo -e "$MSG $@"
-	else
-		echo -e "$@"
-	fi
-}
+	done
 
-# Display errors
-minelib_err () {
-	if [ -n "$1" ]; then
-		local -u MSG_TYPE="$1"
-		local MSG_VAR="ERR_$MSG_TYPE"
-		local CODE_VAR="CODE_$MSG_TYPE"
-		local MSG=${!MSG_VAR}
-		local CODE=${!CODE_VAR}
-
-		if [ -n "$MSG" ]; then
-			if [ -n "$CODE" ]; then
-				shift
-				echo -e "$MSG $@"  1>&2
-				return $CODE
-			else
-				return -1
-			fi
-		else
-			echo -e "$1"
-			if [ -n "$2" ]; then
-				return $2
-			else
-				return 1
-			fi
-		fi
-	else
-		echo -e "[   error   ]" 1>&2
+	# Define debug level, iff undefined
+	if [ -z "$DEBUG_LEVEL" ]; then
+		echo "ERROR: Debug level undefined!" 1>&2
 		return 1
 	fi
-}
 
-# New function for displaying fails
-minelib_fail() {
-	if [ -n "$1" ]; then
-		minelib_err  "$1" "$2"
-		exit $?
-	else
-		echo -e "[  failed   ]" 1>&2
-		exit 1
+	# Print if debug level matches
+	if [ $ON_DEBUG_LEVEL -le $DEBUG_LEVEL ]; then
+		if ( $STDERR ); then
+			echo -e $ECHO_ARGS "$MESSAGE" 1>&2
+		else
+			echo -e $ECHO_ARGS "$MESSAGE"
+		fi
 	fi
-}
-		
+
+	if ( $FAIL ); then
+		exit $RETVAL
+	else
+		return $RETVAL
+	fi
+}		
 
 # List (just) directories in the current folder (without sub directories)
-minelib_ls_dir() {
+_minelib_ls_dir() {
 	local DIR="$1"
 
 	if [ -z "$DIR" ]; then
@@ -175,7 +110,7 @@ minelib_ls_dir() {
 }
 
 # Operate on files
-minelib_fileop() {
+_minelib_fileop() {
 	local GREP="grep"
 	local IGNORE_CASE=false
 	local BEGINS_WITH=false
@@ -183,13 +118,13 @@ minelib_fileop() {
 	local CMD=
 
 	# Add a string to a file
-	minelib_fileop_add() {
+	_minelib_fileop_add() {
 		echo "$PATTERN" >> "$FILE"
 		return $?
 	}
 
 	# Check if a certain string is contained in a file
-	minelib_fileop_contains() {
+	_minelib_fileop_contains() {
 		if ( $BEGINS_WITH && $ENDS_WITH ); then
 			$GREP -E "^[[:blank:]]*$PATTERN[[:blank:]]*$" "$FILE" 2> /dev/null
 		elif ( $BEGINS_WITH ); then
@@ -204,7 +139,7 @@ minelib_fileop() {
 	}
 
 	# Remove a string that is in the beginning of a file from this file
-	minelib_fileop_remove() {
+	_minelib_fileop_remove() {
 		while read MATCH; do
 			local TMP="`mktemp`"		
 			grep -v "$MATCH" "$FILE" > "$TMP" 2> /dev/null
@@ -239,26 +174,28 @@ minelib_fileop() {
 	local FILE="$3"
 
 	case $CMD in
-		contains)	minelib_fileop_contains
+		contains)	_minelib_fileop_contains
 		;;
 		remove)		local TMP_FILE="`mktemp`"
-				minelib_fileop_contains > "$TMP_FILE"
-				minelib_fileop_remove "$TMP_FILE"
+				_minelib_fileop_contains > "$TMP_FILE"
+				_minelib_fileop_remove "$TMP_FILE"
 				rm -f "$TMP_FILE" 2> /dev/null
 		;;
-		add)		minelib_fileop_add
+		add)		_minelib_fileop_add
 		;;
-		*)		minelib_err or "Unknown file operation \"CMD\""
+		*)		print --error "Unknown file operation \"CMD\""
 	esac
 }
 
 # Extract data from a file removing comments and empty lines
-minelib_extract_data() {
-	grep -vE "^[[:blank:]]*$|^[[:blank:]]*#" $1 2> /dev/null
+_minelib_extract_data() {
+	local FILE="$1"
+
+	grep -vE "^[[:blank:]]*$|^[[:blank:]]*#" "$FILE" 2> /dev/null
 }
 
 # Ask a question and return 0 on 'yes' or 1 otherwise
-minelib_ask() {
+_minelib_ask() {
 	local USAGE="\
 	Usage: ask [The question]\nReturns 0 on \"y\" or 1 else."
 
@@ -267,19 +204,11 @@ minelib_ask() {
 		return 2
 	fi
 
+	local MSG="$@"
 	local ANSWER=
 	local RETVAL=1
 
-	local -u MSG_TYPE="$1"
-	local MSG_VAR="ASK_$MSG_TYPE"
-	local MSG=${!MSG_VAR}
-
-	if [ -n "$MSG" ]; then
-		shift
-		echo -en "$MSG $@"
-	else
-		echo -en "$@ "
-	fi
+	echo -en "$MSG"
 
 	# Read and print answer 
 	read ANSWER
@@ -295,7 +224,7 @@ minelib_ask() {
 }
 
 # Change the value of a variable inside a file
-minelib_set_var() {
+_minelib_set_var() {
 	# Arguments for variable name declaration
 	local DECLARE_ARGS=
 
@@ -312,33 +241,33 @@ minelib_set_var() {
 	# The second argument is the file to operate on
 	local FILE="$2"
 
-	local VARIABLE_PURE="`echo "$VAR_DEC" | cut -d "=" -f 1`"
+	local VARIABLE_PURE="$(echo "$VAR_DEC" | cut -d "=" -f 1)"
 	local $DECLARE_ARGS VARIABLE="$VARIABLE_PURE"
-	local VALUE="`echo "$VAR_DEC" | cut -d "=" -f 2`"
+	local VALUE="$(echo "$VAR_DEC" | cut -d "=" -f 2)"
 
 	# Check if variable is not empty
 	if [ -n "$VARIABLE_PURE" ]; then
 		# If the variable name preceeds a "-", that means
 		# we want the variable to be removed from the file
-		if [ -n "`echo "$VARIABLE_PURE" | grep ^"-" 2> /dev/null`" ]; then
+		if [ -n "$(echo "$VARIABLE_PURE" | grep ^"-" 2> /dev/null)" ]; then
 			VARIABLE_PURE="`echo "$VARIABLE_PURE" | cut -d "-" -f 2`"
-			minelib_fileop -b remove "$VARIABLE_PURE" "$FILE" 2> /dev/null
+			_minelib_fileop -b remove "$VARIABLE_PURE" "$FILE" 2> /dev/null
 		else
 			# Search for variable inside the file	
 			local VAR_LINE="`grep ^"$VARIABLE=" "$FILE" 2> /dev/null`"
 
 			# If the variable is in the file, replace it with its new value
-			if ( minelib_fileop -b contains "$VARIABLE=" "$FILE" > /dev/null 2> /dev/null ); then
+			if ( _minelib_fileop -b contains "$VARIABLE=" "$FILE" > /dev/null 2> /dev/null ); then
 				sed -i "s|$VAR_LINE|$VARIABLE=$VALUE|" "$FILE" 2> /dev/null
 			else
-				minelib_fileop add "$VARIABLE=$VALUE" "$FILE"
+				_minelib_fileop add "$VARIABLE=$VALUE" "$FILE"
 			fi
 
 			# Print out the new variable assignment
 			echo "$VARIABLE=$VALUE"
 		fi
 	else
-		minelib_err or "No variable specified"
+		print --error "No variable specified"
 		return 2
 	fi
 	
@@ -347,7 +276,7 @@ minelib_set_var() {
 
 # Print out a file and highlight changes. Usage:
 # print_file [--offset, -o <offset>] <file_name> [change_log]
-minelib_print_file() {
+_minelib_print_file() {
 	local OFFSET=""
 
 	# Check if we specified an offset
@@ -377,7 +306,7 @@ minelib_print_file() {
 		$CONTINUE && continue
 
 		echo -e "$OFFSET$LINE"
-        done < $FILE
+        done < "$FILE"
 }
 
 # Access a server's directory securely
@@ -385,46 +314,116 @@ minelib_print_file() {
 # if a user does not specify a server name by mistake, we will change to $MC_HOME/servers 
 # and, if clean is called "clean()", may remove all servers by mistake. That won't be good!
 # 'access_server' also makes sure that a certain server (directory) exists
-minelib_access_server() {
+_minelib_access_server() {
 	# First parameter is the server name
 	# XXX: This variable needs to be global!
 	SERVER_NAME="$1"
 	
 	# Check is server name is not empty
-	test -n "$SERVER_NAME" 2> /dev/null || minelib_fail no_srv_name
+	test -n "$SERVER_NAME" 2> /dev/null || print --fail no_srv_name
 
 	# Check whether server's directory exists
-	test -d "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || minelib_fail srv_not_existant
+	test -d "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || print --fail srv_not_existant
 
 	# Check whether server's directory is accessible
-	cd "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || minelib_fail access_srv_dir_failed
+	cd "$SERVERS_DIR/$SERVER_NAME" 2> /dev/null || print --fail access_srv_dir_failed
 
 	# Check if we did really change to a subfolder of $MC_HOME/servers
-	test "`dirname $PWD`" == "$SERVERS_DIR" 2> /dev/null || minelib_fail inside_srv_dir
+	test "$(dirname $PWD)" == "$SERVERS_DIR" 2> /dev/null || print --fail inside_srv_dir
 }
 
 # Clean up the server directory
-minelib_clean() {
+_minelib_clean() {
 	# First parameter is the server name
 	SERVER_NAME=$1
 	shift
 
 	# Change to server's directory
-	access_server "$SERVER_NAME"
+	_mineclib_access_server "$SERVER_NAME"
 
 	# Remove server directory's content
-	rm -R * > /dev/null 2> /dev/null || minelib_fail srv_clean_failed
+	rm -R * > /dev/null 2> /dev/null || print --fail srv_clean_failed
 }
 
-# Create named pipes
-minelib_mk_fifos() {
-        for FIFO in $SERVER_STDIN $SERVER_STDOUT $SERVER_STDERR $SERVER_EVENT_QUEUE; do
-                if [ -e $FIFO ]; then
-                        if [ ! -p $FIFO ]; then
-                                minelib_fail file_blocking_pipe
-                        fi
-                else
-                        mkfifo $FIFO
-                fi
-        done
+# Check dependencies
+_minelib_checkdeps() {
+	true
 }
+
+# Test if debug level is verbose
+_minelib_verbose() {
+	test $DEBUG_LEVEL -ge 1 2> /dev/null
+}
+
+# Test if debug level is very verbose
+_minelib_very_verbose() {
+	test $DEBUG_LEVEL -ge 2 2> /dev/null
+}
+
+# Test if a certain function is defined
+_minelib_function_exists() {
+	local FUNCTION_NAME="$1"
+
+	type $FUNCTION_NAME 2> /dev/null | grep -q ^"$1 ()"
+}
+
+###################
+# Public funtions #
+###################
+
+is_int() {
+	_minelib_is_int "$@"
+}
+
+print() {
+	_minelib_print "$@"
+}		
+
+ls_dir() {
+	_minelib_ls_dir "$@"
+}
+
+fileop() {
+	_minelib_fileop "$@"
+}
+
+extract_data() {
+	_minelib_extract_data "$@"
+}
+
+ask() {
+	_minelib_ask "$@"
+}
+
+set_var() {
+	_minelib_set_var "$@"
+}
+
+print_file() {
+	_minelib_print_file "$@"
+}
+
+access_server() {
+	_minelib_access_server "$@"
+}
+
+clean() {
+	_minelib_clean "$@"
+}
+
+checkdeps() {
+	_minelib_checkdeps "$@"
+}
+
+verbose() {
+	_minelib_verbose "$@"
+}
+
+very_verbose() {
+	_minelib_very_verbose "$@"
+}
+
+function_exists() {
+	_minelib_function_exists "$@"
+}
+
