Fixed printout in fail()

diff --git a/src/minelib b/src/minelib
--- a/src/minelib
+++ b/src/minelib
@@ -81,7 +81,7 @@ fail() {
 		err "$@"
 		exit $?
 	else
-		echo -e "[   error   ]" 1>&2
+		echo -e "[  failed   ]" 1>&2
 		exit 1
 	fi
 }
